orders/urls.py
from django.urls import path
from .views import OrderListView, OrderCreateVIew, OrderDetailView

app_name = 'orders'


urlpatterns = [
    path('order-create/', OrderCreateVIew.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('<int:pk>/', OrderDetailView.as_view(), name='order_detail'),

]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from products.models import Basket
from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (ON_WAY, 'On the way'),
        (DELIVERED, 'Delivered'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)


    def __str__(self):
        return f'Order #{self.id}. {self.first_name}, {self.last_name}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product_name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sum = models.DecimalField(max_digits=10, decimal_places=2, default=0)

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ivan'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ivanov'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Russia'}))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

orders/views.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order, OrderItem
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from products.models import Basket


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'U-STYLE Orders'
    queryset = Order.objects.all()

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderCreateVIew(TitleMixin, CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:orders_list')  # Изменено
    title = 'Order making'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user  # Добавляем пользователя в контекст
        return context

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        order = form.save()  # Сохраняем заказ
        basket = Basket.objects.filter(user=self.request.user)
        for item in basket:
            OrderItem.objects.create(  # Создаем объекты OrderItem
                order=order,
                product_name=item.product.name,
                quantity=item.quantity,
                price=item.product.price,
                sum=item.sum()  # Вызываем метод sum()
            )
        basket.delete()  # Очищаем корзину
        return redirect('orders:orders_list')  # Изменено


class OrderDetailView(DetailView):
    model = Order
    template_name = 'orders/order.html' # или другой подходящий шаблон
    context_object_name = 'order'  # имя объекта в контексте шаблона

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
    <section>
    <div class="alert alert-warning text-center" role="alert">
        Please fill in the email address.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Making an order</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Basket</span>
                    <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ basket.product.name }}</h6>
                            <small class="text-muted">{{ basket.quantity }} stuff.</small>
                        </div>
                        <span class="text-muted">{{ basket.sum | intcomma }} rub.</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Paid amount</span>
                        <strong>{{ baskets.total_sum | intcomma }} rub.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Deliver address</h4>
                <form action="{% url 'orders:order_create' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">name</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">lastname</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">email address</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.address.id_for_label }}" class="form-label">address</label>
                            {{ form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Continue</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}

{% load humanize %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Order #{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in order.items.all %}  
                            <tr>
                                <th scope="row"> {{ item.product_name }}</th> 
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.price|intcomma }} r.</td>
                                <td>{{ item.sum|intcomma }} r.</td> 
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p>Total: {{ order.basket_history.total_sum|intcomma }} r.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Orders</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Status</th>
                            <th scope="col">Created</th>
                            <th scope="col">Total</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.status }}</td>
                                <td>{{ order.created }}</td>
                                <td>{{ order.basket_history.total_sum }} rub.</td>
                                <td>
                                    <a href="{% url 'orders:order_detail' order.id %}">see</a> 
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Thank you for order!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Your order has been successfully formed.
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}